class ResultsDisplay:

    @classmethod
    def show(cls, response):
        """
        Print response JSON on screen.
        :param response (JSON): JSON generated by algoritm.
        :return: void
        """
        print(response)